#opyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'
networks:
  default_corda:


services:

  Notary:
    image: cordapp_example
    environment:
      - JAVA_OPTIONS=-Xmx512m
    networks:
      - default_corda
    stdin_open: true
    tty: true
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    command: sh -c 'cd /home/ubuntu/parivesh/samples/cordapp-example/workflows-kotlin/build/nodes/Notary && java -jar corda.jar'
    container_name: Notary


  partyA:
    image: cordapp_example
    environment:
      - JAVA_OPTIONS=-Xmx512m
    networks:
      - default_corda
    stdin_open: true
    tty: true
    ports:
      - "10004:10004"
      - "10005:10005"
      - "10006:10006"
    command: sh -c 'cd /home/ubuntu/parivesh/samples/cordapp-example/workflows-kotlin/build/nodes/PartyA && java -jar corda.jar'
    container_name: partyA

  partyB:
    image: cordapp_example
    environment:
      - JAVA_OPTIONS=-Xmx512m
    networks:
      - default_corda
    stdin_open: true
    tty: true
    ports:
      - "10008:10008"
      - "10009:10009"
      - "10010:10010"
    command: sh -c 'cd /home/ubuntu/parivesh/samples/cordapp-example/workflows-kotlin/build/nodes/PartyB && java -jar corda.jar'
    container_name: partyB

  partyC:
    image: cordapp_example
    environment:
      - JAVA_OPTIONS=-Xmx512m
    networks:
      - default_corda
    stdin_open: true
    tty: true
    ports:
      - "10012:10012"
      - "10013:10013"
      - "10014:10014"
    command: sh -c 'cd /home/ubuntu/parivesh/samples/cordapp-example/workflows-kotlin/build/nodes/PartyC && java -jar corda.jar'
    container_name: partyC
